import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch, useSelector } from 'react-redux'
import { kurang, tambah } from '../features/tambahkurang/tambahkurang.slice'
import { RootState } from '../store'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const tambahKurangState = useSelector((state: RootState) => state.tambahkurang);

  const klikTambah = () => {
    dispatch(tambah())
  }

  const klikKurang = () => {
    dispatch(kurang())
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Tambah Kurang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-5">
        
        <button className="bg-sky-600 px-5 py-3 text-white" onClick={klikKurang}>Kurang</button>
        <b className="mx-3">{tambahKurangState.total}</b>
        <button className="bg-sky-600 px-5 py-3 text-white" onClick={klikTambah}>Tambah</button>

      </div>
    </div>
  )
}

export default Home
